services:
  svc1:
    image: gamesf2pmode/webapp
    ports:
      - "8080:80" 
  svc2: 
    image: gamesf2pmode/foodapp    
    ports:
      - "8081:80"
  svc3:
    image: nginx    
    ports:
      - "8082:80"
    volumes:
      - /home/lms-build-server/app-services-1/ecommapp:/usr/share/nginx/html  
