# - Comment, this line will be ignored by Kubernetes

# we can use .yml or .yaml for Kubernetes Manifest File(CODE)

# Correct Representation of Key Values
key: value 

# Incorrect Representation of Key Values
key:value 
key :value

# Simple Key Values
name: venky
city: waterloo
province/state: ontario
country: canada

# Dictionary / Map - A dictionary is a data structure that holds a collection of data as a set of key-value pairs.

student:
  name: venky
  city: waterloo
  province: ontario

